Integrated the following from //depot/zimbra/HELIX/...: Change 479813 by quanah@qhelix on 2013/08/09 16:12:51
bug: 82712
Fix copyright block

http://bugzilla.zimbra.com/show_bug.cgi?id=82712

Copied from Perforce
 Change: 479815

diff --git a/src/bin/postfix b/src/bin/postfix
--- a/src/bin/postfix
+++ b/src/bin/postfix
@@ -2,7 +2,7 @@
 # 
 # ***** BEGIN LICENSE BLOCK *****
 # Zimbra Collaboration Suite Server
-# Copyright (C) 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Zimbra Software, LLC.
+# Copyright (C) 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2013 VMware, Inc.
 # 
 # The contents of this file are subject to the Zimbra Public License
 # Version 1.3 ("License"); you may not use this file except in
@@ -17,6 +17,12 @@
 progdir=`dirname $0`
 
 source `dirname $0`/zmshutil || exit 1
+
+if [ ! -L /opt/zimbra/postfix ]; then
+  echo "Error: postfix not installed"
+  exit 1
+fi
+
 zmsetvars \
 	zimbra_home \
   postfix_mail_owner \
diff --git a/src/bin/zmmemcachedctl b/src/bin/zmmemcachedctl
--- a/src/bin/zmmemcachedctl
+++ b/src/bin/zmmemcachedctl
@@ -2,7 +2,7 @@
 # 
 # ***** BEGIN LICENSE BLOCK *****
 # Zimbra Collaboration Suite Server
-# Copyright (C) 2008, 2009, 2010, 2011 Zimbra Software, LLC.
+# Copyright (C) 2008, 2009, 2010, 2013 VMware, Inc.
 # 
 # The contents of this file are subject to the Zimbra Public License
 # Version 1.3 ("License"); you may not use this file except in
@@ -54,6 +54,11 @@ checkrunning()
 
 case "$1" in 
   start)
+
+    if [ ! -L /opt/zimbra/memcached ]; then
+      echo "Error: memcached not installed"
+      exit 1
+    fi
 
     checkrunning
     echo -n "Starting ${servicename}..."
diff --git a/src/bin/zmmtactl b/src/bin/zmmtactl
--- a/src/bin/zmmtactl
+++ b/src/bin/zmmtactl
@@ -2,7 +2,7 @@
 # 
 # ***** BEGIN LICENSE BLOCK *****
 # Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2011 Zimbra Software, LLC.
+# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2012, 2013 VMware, Inc.
 # 
 # The contents of this file are subject to the Zimbra Public License
 # Version 1.3 ("License"); you may not use this file except in
@@ -21,6 +21,11 @@ zmsetvars \
 	zimbra_server_hostname 
 
 BASE=${zimbra_home:=/opt/zimbra}
+
+if [ ! -L /opt/zimbra/postfix ]; then
+  echo "Error: postfix not installed"
+  exit 1
+fi
 
 if [ -f "${zimbra_home}/conf/mta_milter_options" ]; then
   source ${zimbra_home}/conf/mta_milter_options
@@ -41,7 +46,7 @@ rewriteconfig() {
       ${zimbra_home}/bin/postconf -e mail_owner=${postfix_mail_owner} setgid_group=${postfix_setgid_group}
     fi
   fi
-  /opt/zimbra/libexec/configrewrite antispam antivirus mta sasl  > /dev/null 2>&1
+  /opt/zimbra/libexec/configrewrite antispam antivirus opendkim mta sasl  > /dev/null 2>&1
   if [ $? = 0 ]; then
     echo "done."
   else
