Integrated the following from //depot/zimbra/IRONMAIDEN/...: Change 511124 by tpubliski@katbert on 2014/05/09 12:35:03
Bug: 90032

Stop attempting to perform mailboxd-related tasks if we cannot determine the pid.

http://bugzilla.zimbra.com/show_bug.cgi?id=90032

Copied from Perforce
 Change: 511128

diff --git a/src/bin/zmamavisdctl b/src/bin/zmamavisdctl
--- a/src/bin/zmamavisdctl
+++ b/src/bin/zmamavisdctl
@@ -27,18 +27,14 @@ export LD_LIBRARY_PATH=/opt/zimbra/openldap/lib:/opt/zimbra/openssl/lib:$LD_LIBR
 
 source `dirname $0`/zmshutil || exit 1
 zmsetvars \
-  zimbra_home \
   zimbra_log_directory
 
 platform=`/opt/zimbra/libexec/get_plat_tag.sh`
 pidfile=${zimbra_log_directory}/amavisd.pid
+mcpidfile=${zimbra_log_directory}/amavis-mc.pid
 
 if [ ! -d "/opt/zimbra/data/amavisd/.spamassassin" ]; then
     mkdir -p /opt/zimbra/data/amavisd/.spamassassin
-fi
-
-if [ ! -d "/opt/zimbra/data/amavisd/db" ]; then
-    mkdir -p /opt/zimbra/data/amavisd/db
 fi
 
 rewriteconfig() {
@@ -80,14 +76,55 @@ checkrunning() {
   fi
 }
 
+checkrunning-mc() {
+  # amavisd (master) should be listed in the $pidfile.
+  if [ -f $mcpidfile ]; then
+    MCPID=`cat $mcpidfile`
+  fi
+  #  If no PID file or PID file is empty, then get PID from scanning the proc table.
+  if [ "x$MCPID" = "x" ]; then
+    # PID file is NULL.  Get info from proc table.
+    MCPID=`/bin/ps axo user,pid,ppid,command | awk '{ if ((($6 ~ /amavis-mc$/) || ($6 ~ /\/opt\/zimbra\/amavisd\/sbin\/amavis-mc$/))) { print $2 } }'`
+  fi
+  # If PID is still not set, then we cannot find any amavisd (master) process.  Assume amavisd is not running.
+  if [ "x$MCPID" = "x" ]; then
+    MCRUNNING=0
+    return
+  fi
+
+  MCRUNNING=1
+  return
+}
+
 
 #
 # Main
 #
 case "$1" in
   'start')
+    checkrunning-mc
+    echo -n "Starting amavisd-mc..."
+    if [ $MCRUNNING = 1 ]; then
+      echo "amavisd-mc is already running."
+    else
+      if [ $MCRUNNING = 0 ]; then
+        sudo /opt/zimbra/amavisd/sbin/amavis-mc
+        for ((i=0; i < 30; i++)); do
+          checkrunning-mc
+          if [ $MCRUNNING = 1 ]; then 
+            break
+          fi  
+          sleep 1
+        done
+      fi
+      if [ "x$MCPID" = "x" ]; then
+        echo "failed."
+        exit
+      else 
+        echo "done."
+      fi 
+    fi
     checkrunning
-  
     echo -n "Starting amavisd..."
     if [ $RUNNING = 1 ]; then
       echo "amavisd is already running."
@@ -95,16 +132,6 @@ case "$1" in
     else
       if [ ! -d /opt/zimbra/data/amavisd/quarantine ]; then
         mkdir /opt/zimbra/data/amavisd/quarantine
-      fi
-      if [ ! -d /opt/zimbra/data/amavisd/db ]; then
-        mkdir /opt/zimbra/data/amavisd/db
-      fi
-      if [ ! -f /opt/zimbra/data/amavisd/db/DB_CONFIG -o ! -s /opt/zimbra/data/amavisd/db/DB_CONFIG ]; then
-        if [ -f /opt/zimbra/conf/custom/amavisd/DB_CONFIG ]; then
-          cp -f /opt/zimbra/conf/custom/amavisd/DB_CONFIG /opt/zimbra/data/amavisd/db/DB_CONFIG
-        else
-          cp -f /opt/zimbra/amavisd/DB_CONFIG.amavisd /opt/zimbra/data/amavisd/db/DB_CONFIG
-        fi
       fi
       if [ ! -d /opt/zimbra/data/amavisd/tmp ]; then
         mkdir /opt/zimbra/data/amavisd/tmp
@@ -117,14 +144,14 @@ case "$1" in
       if [ x$2 = "x" ]; then
         rewriteconfig
       fi
-      if [ ! -f ${zimbra_home}/data/amavisd/.spamassassin/bayes_toks ]; then
+      if [ ! -f /opt/zimbra/data/amavisd/.spamassassin/bayes_toks ]; then
         # Initial bayes seeding.
-        cp -f ${zimbra_home}/amavisd/.spamassassin/init/* \
-          ${zimbra_home}/data/amavisd/.spamassassin/
-        chmod 644 ${zimbra_home}/data/amavisd/.spamassassin/bayes*
+        cp -f /opt/zimbra/amavisd/.spamassassin/init/* \
+          /opt/zimbra/data/amavisd/.spamassassin/
+        chmod 644 /opt/zimbra/data/amavisd/.spamassassin/bayes*
       fi
-      ${zimbra_home}/amavisd/sbin/amavisd -c \
-        ${zimbra_home}/conf/amavisd.conf &
+      /opt/zimbra/amavisd/sbin/amavisd -X no_conf_file_writable_check -c \
+        /opt/zimbra/conf/amavisd.conf &
       for ((i=0; i < 30; i++)); do
         checkrunning
         if [ $RUNNING = 1 ]; then 
@@ -149,23 +176,42 @@ case "$1" in
     echo -n "Stopping amavisd..."
     if [ $RUNNING = 0 ]; then
       echo "amavisd is not running."
-      exit 0
     else 
       kill -TERM $PID 2> /dev/null
       for ((i=0; i < 300; i++)); do
         sleep 5
         kill -0 $PID 2> /dev/null
         if [ $? != 0 ]; then
-          echo " done."
-          exit 0
+          break
         fi
       done
       kill -TERM $PID 2> /dev/null
-      if [ $? = 0 ]; then
+      if [ $? != 0 ]; then
+        echo " done."
+      else 
         echo " failed to stop $PID"
         exit 1
-      else 
+      fi
+    fi
+    checkrunning-mc
+    echo -n "Stopping amavisd-mc..."
+    if [ $MCRUNNING = 0 ]; then
+      echo "amavisd-mc is not running."
+    else
+      kill -TERM $MCPID 2> /dev/null
+      for ((i=0; i < 300; i++)); do
+        sleep 5
+        kill -0 $MCPID 2> /dev/null
+        if [ $? != 0 ]; then
+          break
+        fi
+      done
+      kill -TERM $MCPID 2> /dev/null
+      if [ $? != 0 ]; then
         echo " done."
+      else 
+        echo " failed to stop $PID"
+        exit 1
       fi
     fi
     exit 0
@@ -180,6 +226,14 @@ case "$1" in
     checkrunning
     echo -n "amavisd is "
     if [ $RUNNING = 0 ]; then
+      echo "not running."
+      exit 1
+    else
+      echo "running."
+    fi
+    checkrunning-mc
+    echo -n "amavisd-mc is "
+    if [ $MCRUNNING = 0 ]; then
       echo "not running."
       exit 1
     else
diff --git a/src/bin/zmmemcachedctl b/src/bin/zmmemcachedctl
--- a/src/bin/zmmemcachedctl
+++ b/src/bin/zmmemcachedctl
@@ -2,7 +2,7 @@
 # 
 # ***** BEGIN LICENSE BLOCK *****
 # Zimbra Collaboration Suite Server
-# Copyright (C) 2008, 2009, 2010, 2012, 2013 Zimbra Software, LLC.
+# Copyright (C) 2008, 2009, 2010, 2013 Zimbra Software, LLC.
 # 
 # The contents of this file are subject to the Zimbra Public License
 # Version 1.4 ("License"); you may not use this file except in
@@ -21,11 +21,10 @@ fi
 
 source `dirname $0`/zmshutil || exit 1
 zmsetvars \
-    zimbra_home \
     zimbra_log_directory
 
 servicename=memcached
-configfile=${zimbra_home}/conf/${servicename}.conf
+configfile=/opt/zimbra/conf/${servicename}.conf
 pidfile=${zimbra_log_directory}/${servicename}.pid
 pid=""
 
@@ -55,6 +54,11 @@ checkrunning()
 case "$1" in 
   start)
 
+    if [ ! -L /opt/zimbra/memcached ]; then
+      echo "Error: memcached not installed"
+      exit 1
+    fi
+
     checkrunning
     echo -n "Starting ${servicename}..."
     if [ $running = 1 ]; then
@@ -62,7 +66,7 @@ case "$1" in
       exit 0
     fi
 
-    ${zimbra_home}/${servicename}/bin/${servicename} -d -P ${pidfile}
+    /opt/zimbra/${servicename}/bin/${servicename} -d -P ${pidfile}
     for ((i=0; i < 30; i++)); do
       checkrunning
       if [ $running = 1 ]; then
diff --git a/src/bin/zmmtactl b/src/bin/zmmtactl
--- a/src/bin/zmmtactl
+++ b/src/bin/zmmtactl
@@ -15,15 +15,19 @@
 # 
 source `dirname $0`/zmshutil || exit 1
 zmsetvars \
-	zimbra_home \
   postfix_mail_owner \
   postfix_setgid_group \
-	zimbra_server_hostname 
+	zimbra_server_hostname
 
-BASE=${zimbra_home:=/opt/zimbra}
+BASE=/opt/zimbra
 
-if [ -f "${zimbra_home}/conf/mta_milter_options" ]; then
-  source ${zimbra_home}/conf/mta_milter_options
+if [ ! -L /opt/zimbra/postfix ]; then
+  echo "Error: postfix not installed"
+  exit 1
+fi
+
+if [ -f "/opt/zimbra/conf/mta_milter_options" ]; then
+  source /opt/zimbra/conf/mta_milter_options
 fi
 zimbraMilterServerEnabled=${zimbraMilterServerEnabled:=FALSE}
 
@@ -37,10 +41,10 @@ fi
 
 rewriteconfig() {
   echo -n "Rewriting configuration files..."
-  if [ -L ${zimbra_home}/postfix ]; then
-    if [ ! -f ${zimbra_home}/postfix/conf/main.cf ]; then
-      touch ${zimbra_home}/postfix/conf/main.cf
-      ${zimbra_home}/bin/postconf -e mail_owner=${postfix_mail_owner} setgid_group=${postfix_setgid_group}
+  if [ -L /opt/zimbra/postfix ]; then
+    if [ ! -f /opt/zimbra/postfix/conf/main.cf ]; then
+      touch /opt/zimbra/postfix/conf/main.cf
+      /opt/zimbra/bin/postconf -e mail_owner=${postfix_mail_owner} setgid_group=${postfix_setgid_group}
     fi
   fi
   /opt/zimbra/libexec/configrewrite antispam antivirus opendkim mta sasl  > /dev/null 2>&1
