bug: 41040
integrate change 211424 from FRANKLIN to main
----------------------------------------------
Change 211424 by pshao@pshao-mac on 2009/09/17 08:11:35

        bug: 41040

        throw PERM_DENIED for delegated request if the requested account does not exist.

http://bugzilla.zimbra.com/show_bug.cgi?id=41040

Copied from Perforce
 Change: 211428

diff --git a/src/bin/zmapachectl b/src/bin/zmapachectl
--- a/src/bin/zmapachectl
+++ b/src/bin/zmapachectl
@@ -1,9 +1,8 @@
 #!/bin/bash
 # 
 # ***** BEGIN LICENSE BLOCK *****
-# 
 # Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2007 Zimbra, Inc.
+# Copyright (C) 2005, 2007, 2008 Zimbra, Inc.
 # 
 # The contents of this file are subject to the Yahoo! Public License
 # Version 1.0 ("License"); you may not use this file except in
@@ -12,7 +11,6 @@
 # 
 # Software distributed under the License is distributed on an "AS IS"
 # basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
-# 
 # ***** END LICENSE BLOCK *****
 # 
 
@@ -24,27 +22,49 @@ PIDFILE=$BASE/log/httpd.pid
 case "$1" in
 	start)
 		if [ -f $APACHECTL ]; then
+      echo -n "Starting apache..."
 			$APACHECTL -k $1 -f $CONF
-			exit $?
+      status=$?
+      if [ $status = 0 ]; then
+        echo "done."
+      else
+        echo "failed."
+      fi
+			exit $status
 		fi
 		exit 0
 	;;
   reload|graceful)
 		if [ -f $APACHECTL ]; then
+      echo -n "Reloading apache..."
 			$APACHECTL -k graceful -f $CONF
-			exit $?
+      status=$?
+      if [ $status = 0 ]; then
+        echo "done."
+      else
+        echo "failed."
+      fi
+			exit $status
 		fi
 		exit 0
 	;;
   restart)
     $0 stop
+    sleep 1
     $0 start
   ;;
 	stop)
 		if [ -f $PIDFILE ]; then
 			if [ -f $APACHECTL ]; then
+        echo -n "Stopping apache..."
 				$APACHECTL -k $1 -f $CONF
-				exit $?
+        status=$?
+        if [ $status = 0 ]; then
+          echo "done."
+        else
+          echo "failed."
+        fi
+			  exit $status
 			fi
 		fi
 		exit 0
@@ -53,19 +73,19 @@ case "$1" in
     if [ -f $PIDFILE ]; then
 		  pid=$(cat $PIDFILE)
       if [ x"$pid" = "x" ]; then
-        echo "Apache not running."
+        echo "apache is not running."
         exit 1
       fi
     else
-      echo "Apache not running.  No PID file found."
+      echo "apache is not running."
       exit 1
     fi
 		kill -0 $pid
     if [ $? = 0 ]; then
-      echo "Apache running with PID $pid"
+      echo "apache is running."
       exit 0
     else 
-      echo "Apache not running."
+      echo "apache is not running."
 		  exit 1
     fi
 	;;
diff --git a/src/bin/zmtlsctl b/src/bin/zmtlsctl
--- a/src/bin/zmtlsctl
+++ b/src/bin/zmtlsctl
@@ -1,9 +1,8 @@
 #!/bin/bash
 # 
 # ***** BEGIN LICENSE BLOCK *****
-# 
 # Zimbra Collaboration Suite Server
-# Copyright (C) 2005, 2006, 2007 Zimbra, Inc.
+# Copyright (C) 2005, 2006, 2007, 2008 Zimbra, Inc.
 # 
 # The contents of this file are subject to the Yahoo! Public License
 # Version 1.0 ("License"); you may not use this file except in
@@ -12,7 +11,6 @@
 # 
 # Software distributed under the License is distributed on an "AS IS"
 # basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
-# 
 # ***** END LICENSE BLOCK *****
 # 
 
@@ -49,6 +47,7 @@ fi
 case "$1" in
   mixed|both|http|https|redirect)
     MODE=$1
+    UPDATE_MAIL_MODE=1
     ;;
   help|--help|-help)
     echo "Usage: $0 [mixed|both|http|https|redirect]"
@@ -65,7 +64,7 @@ esac
 export JAVA_HOME=${zimbra_java_home}
 
 if [ "x${zimbra_tmp_directory}" = "x" ]; then
-  zimbra_tmp_directory=/tmp
+  zimbra_tmp_directory=$zimbra_home/data/tmp
 fi
 
 if [ ! -d ${zimbra_tmp_directory} ]; then
@@ -77,17 +76,26 @@ if [ "x$zimbra_server_hostname" = "x" ]; then
   exit 1;
 fi
 
-${zimbra_home}/bin/zmprov -l gs ${zimbra_server_hostname} > /dev/null 2>&1
-if [ $? != 0 ]; then
-  echo "ERROR: problem reading config from ldap. Make sure ldap is running."
-  exit 1
-fi
-
 if [ "x$MODE" = "x" ]; then
 	MODE=`${zimbra_home}/bin/zmprov -l gs ${zimbra_server_hostname} 2> /dev/null | grep zimbraMailMode | sed -e 's/zimbraMailMode: //'`
 
+  if [ $? != 0 ]; then
+    echo "ERROR: problem reading config from ldap. Make sure ldap is running."
+    exit 1
+  fi
+
 	if [ "x$MODE" = "x" ]; then
 		MODE="http"
+	fi
+else
+	shift
+fi
+
+if [ "x$DEBUG" = "x" ]; then
+	DEBUG=`${zimbra_home}/bin/zmprov -l gs ${zimbra_server_hostname} zimbraHttpDebugHandlerEnabled | grep zimbraHttpDebugHandlerEnabled | sed -e 's/zimbraHttpDebugHandlerEnabled: //' | tr A-Z a-z`
+
+	if [ "x$DEBUG" = "x" ]; then
+		DEBUG="false"
 	fi
 else
 	shift
@@ -150,6 +158,23 @@ updateJettyConfig() {
       exit 1
     fi
 
+    origfile=${mailboxd_conf_directory}/service.web.xml.in
+    tempfile=$(mktemp ${origfile}.XXXXXX) && cp -f ${origfile} ${tempfile}
+    if [ $? = 0 -a -s "${tempfile}" ]; then
+      echo -n "Updating ${origfile}..."
+		  sed -e 's/\(.*REDIRECTBEGIN\).*/\1/' -e 's/.*\(REDIRECTEND.*\)/\1/' \
+			  ${origfile} > ${tempfile} && mv -f ${tempfile} ${origfile}
+      if [ $? = 0 ]; then
+        echo "done."
+      else 
+        echo "failed."
+        exit 1
+      fi
+    else
+      echo "Couldn't create tempfile for ${origfile}"
+      exit 1
+    fi
+
     origfile=${jetty_web_xml}/zimbra.web.xml.in
     tempfile=$(mktemp ${origfile}.XXXXXX) && cp -f ${origfile} ${tempfile}
     if [ $? = 0 -a -s "${tempfile}" ]; then
@@ -192,6 +217,23 @@ updateJettyConfig() {
       echo -n "Updating ${origfile}..."
 		  sed -e 's/\(.*HTTPSBEGIN\).*/\1 -->/' -e 's/.*\(HTTPSEND.*\)/<!-- \1/' \
 			  -e 's/\(.*HTTPBEGIN\).*/\1/' -e 's/.*\(HTTPEND.*\)/\1/' \
+			  ${origfile} > ${tempfile} && mv -f ${tempfile} ${origfile}
+      if [ $? = 0 ]; then
+        echo "done."
+      else 
+        echo "failed."
+        exit 1
+      fi
+    else
+      echo "Couldn't create tempfile for ${origfile}"
+      exit 1
+    fi
+
+    origfile=${mailboxd_conf_directory}/service.web.xml.in
+    tempfile=$(mktemp ${origfile}.XXXXXX) && cp -f ${origfile} ${tempfile}
+    if [ $? = 0 -a -s "${tempfile}" ]; then
+      echo -n "Updating ${origfile}..."
+		  sed -e 's/\(.*REDIRECTBEGIN\).*/\1/' -e 's/.*\(REDIRECTEND.*\)/\1/' \
 			  ${origfile} > ${tempfile} && mv -f ${tempfile} ${origfile}
       if [ $? = 0 ]; then
         echo "done."
@@ -260,6 +302,23 @@ updateJettyConfig() {
       exit 1
     fi
 
+    origfile=${mailboxd_conf_directory}/service.web.xml.in
+    tempfile=$(mktemp ${origfile}.XXXXXX) && cp -f ${origfile} ${tempfile}
+    if [ $? = 0 -a -s "${tempfile}" ]; then
+      echo -n "Updating ${origfile}..."
+		  sed -e 's/\(.*REDIRECTBEGIN\).*/\1 -->/' -e 's/.*\(REDIRECTEND.*\)/<!-- \1/' \
+			  ${origfile} > ${tempfile} && mv -f ${tempfile} ${origfile}
+      if [ $? = 0 ]; then
+        echo "done."
+      else 
+        echo "failed."
+        exit 1
+      fi
+    else
+      echo "Couldn't create tempfile for ${origfile}"
+      exit 1
+    fi
+
     origfile=${jetty_web_xml}/zimbra.web.xml.in
     tempfile=$(mktemp ${origfile}.XXXXXX) && cp -f ${origfile} ${tempfile}
     if [ $? = 0 -a -s "${tempfile}" ]; then
@@ -302,6 +361,23 @@ updateJettyConfig() {
       echo -n "Updating ${origfile}..."
 		  sed -e 's/\(.*HTTPSBEGIN\).*/\1 -->/' -e 's/.*\(HTTPSEND.*\)/<!-- \1/' \
 			  -e 's/\(.*HTTPBEGIN\).*/\1 -->/' -e 's/.*\(HTTPEND.*\)/<!-- \1/' \
+			  ${origfile} > ${tempfile} && mv -f ${tempfile} ${origfile}
+      if [ $? = 0 ]; then
+        echo "done."
+      else 
+        echo "failed."
+        exit 1
+      fi
+    else
+      echo "Couldn't create tempfile for ${origfile}"
+      exit 1
+    fi
+
+    origfile=${mailboxd_conf_directory}/service.web.xml.in
+    tempfile=$(mktemp ${origfile}.XXXXXX) && cp -f ${origfile} ${tempfile}
+    if [ $? = 0 -a -s "${tempfile}" ]; then
+      echo -n "Updating ${origfile}..."
+		  sed -e 's/\(.*REDIRECTBEGIN\).*/\1/' -e 's/.*\(REDIRECTEND.*\)/\1/' \
 			  ${origfile} > ${tempfile} && mv -f ${tempfile} ${origfile}
       if [ $? = 0 ]; then
         echo "done."
@@ -385,14 +461,42 @@ updateJettyConfig() {
     fi
 	fi
 
-  echo -n "Rewriting config files for webxml and mailboxd..."
-  ${zimbra_home}/libexec/zmmtaconfig webxml mailbox  > /dev/null 2>&1
-  if [ $? = 0 ]; then
-    echo "done."
-  else
-    echo "failed."
-    exit 1
+	if [ x"$DEBUG" = "xtrue" ]; then
+    origfile=${mailboxd_conf_directory}/jetty.xml.in
+    tempfile=$(mktemp ${origfile}.XXXXXX) && cp -f ${origfile} ${tempfile}
+    if [ $? = 0 -a -s "${tempfile}" ]; then
+      echo -n "Enabling debug handler ${origfile}..."
+	    sed -e 's/\(.*DEBUGBEGIN\).*/\1 -->/' -e 's/.*\(DEBUGEND.*\)/<!-- \1/' \
+		    ${origfile} > ${tempfile} && mv -f ${tempfile} ${origfile}
+      if [ $? = 0 ]; then
+        echo "done."
+      else 
+        echo "failed."
+        exit 1
+      fi
+    else
+      echo "Couldn't create tempfile for ${origfile}"
+      exit 1
+    fi
+  else 
+    origfile=${mailboxd_conf_directory}/jetty.xml.in
+    tempfile=$(mktemp ${origfile}.XXXXXX) && cp -f ${origfile} ${tempfile}
+    if [ $? = 0 -a -s "${tempfile}" ]; then
+      echo -n "Disabling debug handler ${origfile}..."
+	    sed -e 's/\(.*DEBUGBEGIN\).*/\1/' -e 's/.*\(DEBUGEND.*\)/\1/' \
+		    ${origfile} > ${tempfile} && mv -f ${tempfile} ${origfile}
+      if [ $? = 0 ]; then
+        echo "done."
+      else 
+        echo "failed."
+        exit 1
+      fi
+    else
+      echo "Couldn't create tempfile for ${origfile}"
+      exit 1
+    fi
   fi
+
 }
 
 updateSASLConfig() {
@@ -435,8 +539,11 @@ updateSASLConfig() {
       fi
 		fi
 	fi
-  echo -n "Rewriting config files for cyrus-sasl..."
-  ${zimbra_home}/libexec/zmmtaconfig sasl > /dev/null 2>&1
+}
+
+rewriteConfigs() {
+  echo -n "Rewriting config files for cyrus-sasl, webxml and mailboxd..."
+  ${zimbra_home}/libexec/zmmtaconfig sasl webxml mailbox  > /dev/null 2>&1
   if [ $? = 0 ]; then
     echo "done."
   else
@@ -462,4 +569,8 @@ else
   updateJettyConfig
 fi
 updateSASLConfig
-updateLdap
+rewriteConfigs
+
+if [ x"$UPDATE_MAIL_MODE" = "x1" ]; then
+  updateLdap
+fi
