bug: 27943
integrate change 152509 from FRANKLIN to main
----------------------------------------------
Change 152509 by pshao@pshao-mac on 2009/04/03 20:23:22

        bug: 27943

        - do not default zimbraPrefMailDefaultCharset to UTF8
        - do not mandate a value on cos in the callback for zimbraPrefMailDefaultCharset.

http://bugzilla.zimbra.com/show_bug.cgi?id=27943

Copied from Perforce
 Change: 152510

diff --git a/src/bin/zmcertmgr b/src/bin/zmcertmgr
--- a/src/bin/zmcertmgr
+++ b/src/bin/zmcertmgr
@@ -1,9 +1,8 @@
 #!/bin/bash
 # 
 # ***** BEGIN LICENSE BLOCK *****
-# 
 # Zimbra Collaboration Suite Server
-# Copyright (C) 2007 Zimbra, Inc.
+# Copyright (C) 2007, 2008, 2009 Zimbra, Inc.
 # 
 # The contents of this file are subject to the Yahoo! Public License
 # Version 1.0 ("License"); you may not use this file except in
@@ -12,7 +11,6 @@
 # 
 # Software distributed under the License is distributed on an "AS IS"
 # basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
-# 
 # ***** END LICENSE BLOCK *****
 # 
 
@@ -30,6 +28,7 @@ zmsetvars -f \
   zimbra_server_hostname \
   zimbra_tmp_directory \
   zimbra_java_home \
+  zimbra_zmcertmgr_expiration_threshold \
   ldap_is_master \
   mailboxd_directory \
   mailboxd_server \
@@ -50,6 +49,8 @@ fi
 
 zimbra_home=${zimbra_home:=/opt/zimbra}
 zimbra_conf_directory=${zimbra_home}/conf
+exp_thres_days=${zimbra_zmcertmgr_expiration_threshold:=30}
+exp_thres_secs=$(($exp_thres_days*24*60*60))
 
 csr_download_directory=${zimbra_home}/mailboxd/webapps/zimbraAdmin/tmp
 csr_download_file=${csr_download_directory}/current.csr
@@ -362,8 +363,38 @@ createKeystore () {
   rm -f ${tmpfile} 2> /dev/null
 }
 
+addCACERT() {
+  crt=$1
+  alias=zcs-user-$(basename $crt .crt)
+
+  if [ ! -f "${crt}" ]; then
+    usage
+    return
+  fi
+  
+
+  echo -n "** Importing certificate ${crt} to CACERTS as $alias..."
+  tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "Failed to create tmpfile" && exit 1)
+  ${zimbra_java_home}/bin/keytool -delete -alias ${alias} -keystore ${CACERTS} -storepass ${mailboxd_truststore_password} > /dev/null 2>&1
+  ${zimbra_java_home}/bin/keytool -import -noprompt -keystore ${CACERTS} -file ${crt} -alias ${alias} -storepass ${mailboxd_truststore_password} > ${tmpfile} 2>&1
+  if [ $? != 0 ]; then
+    echo "failed."
+    echo "${ERROR_PREFIX} failed to import certficate."
+    echo
+    cat $tmpfile
+    echo
+    rm -f $tmpfile 2>/dev/null
+    exit 1
+  else
+    echo "done."
+    echo "** NOTE: mailboxd must be restarted in order to use the imported certificate."
+  fi
+  rm -f $tmpfile 2>/dev/null
+
+}
 
 updateCACERTS() {
+
   echo -n "** Importing CA ${zimbra_ca_crt} into CACERTS..."
   tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "Failed to create tmpfile" && exit 1)
   ${zimbra_java_home}/bin/keytool -delete -alias my_ca -keystore ${CACERTS} -storepass ${mailboxd_truststore_password} > /dev/null 2>&1
@@ -914,10 +945,10 @@ createCert() {
 
 viewstagedcrt() {
   if [ x"${1}" = "x" ]; then
-    if [ -f "${zimbra_home}/conf/slapd.crt" ]; then
-      current_crt=${zimbra_home}/conf/slapd.crt
-    elif [ -f "${zimbra_home}/conf/smtpd.crt" ]; then
-      current_crt=${zimbra_home}/conf/smtpd.crt
+    if [ -f "${commercial_crt}" ]; then
+      current_crt=${commercial_crt}
+    elif [ -f "${server_crt}" ]; then
+      current_crt=${server_crt}
     else
       usage
     fi
@@ -962,6 +993,99 @@ getsubjectaltnames() {
 
   names=`${openssl} $req -in ${cert} -text | sed -n '/Subject Alternative Name/{n;p;}' | sed 's/^[ \t]*//' | sed 's/DNS://g'`
   echo "SubjectAltName= $names"
+}
+
+checkCertExpiration() {
+
+  if [ "x$1" = "x-days" ]; then
+    shift
+    exp_thres_days=$1
+    shift
+    exp_thres_secs=$((exp_thres_days*24*60*60))
+  fi 
+
+  if [ "x$1" = "x" ]; then
+    VIEW="all"
+  elif [ "x$1" = "xall" -o "x$1" = "xmta" -o "x$1" = "xproxy" -o "x$1" = "xmailboxd" -o "x$1" = "xldap" ]; then
+    VIEW="$1"
+  else
+    echo "${ERROR_PREFIX} Can't verify cert expiration for $1.  Unknown service."
+    return
+  fi
+
+  if [ $VIEW = "all" -o $VIEW = "mta" ]; then
+    service_crt=/opt/zimbra/conf/smtpd.crt
+    #echo "::service mta::"
+    if [ -f "${service_crt}" ]; then
+      ${openssl} x509  -in ${service_crt} -noout -checkend ${exp_thres_secs}
+      if [ $? != 0 ]; then
+        status=1
+        echo "${service_crt} is expiring within ${exp_thres_days} days."
+        ${openssl} x509  -in ${service_crt} -enddate -noout 
+      fi
+    else 
+      echo "${ERROR_PREFIX} ${service_crt} does not exist"
+    fi
+  fi
+
+  if [ $VIEW = "all" -o $VIEW = "proxy" ]; then
+    service_crt=/opt/zimbra/conf/nginx.crt
+    #echo "::service proxy::"
+    if [ -f "${service_crt}" ]; then
+      ${openssl} x509  -in ${service_crt} -noout -checkend ${exp_thres_secs}
+      if [ $? != 0 ]; then
+        status=1
+        echo "${service_crt} is expiring within ${exp_thres_days} days."
+        ${openssl} x509  -in ${service_crt} -enddate -noout 
+      fi
+    else 
+      echo "${ERROR_PREFIX} ${service_crt} does not exist"
+    fi
+  fi
+  
+  if [ $VIEW = "all" -o $VIEW = "mailboxd" ]; then
+    service_der=/opt/zimbra/mailboxd/etc/mailboxd.der
+    service_crt=/opt/zimbra/mailboxd/etc/mailboxd.pem
+    #echo "::service mailboxd::"
+    tmpfile=`mktemp -t zmcertmgr.XXXXXX 2> /dev/null` || (echo "${ERROR_PREFIX} Failed to create tmpfile" && exit 1)
+    ${zimbra_java_home}/bin/keytool -export -file ${service_der} -alias ${mailboxd_server} \
+      -keystore ${mailboxd_keystore} -storepass ${mailboxd_keystore_password} > ${tmpfile} 2>&1
+    if [ $? != 0 ]; then
+      echo "${ERROR_PREFIX} failed to export ${service_crt} from keystore."
+      echo
+      cat $tmpfile
+      echo
+    fi
+    rm -f $tmpfile 2>/dev/null
+    if [ -f "${service_der}" ]; then
+      ${openssl} x509  -inform DER -outform PEM -in ${service_der} -out ${service_crt}
+      ${openssl} x509  -in ${service_crt} -noout -checkend ${exp_thres_secs}
+      if [ $? != 0 ]; then
+        status=1
+        echo "${service_crt} is expiring within ${exp_thres_days} days."
+        ${openssl} x509  -in ${service_crt} -enddate -noout 
+      fi
+    else 
+      echo "${ERROR_PREFIX} ${service_crt} does not exist"
+    fi
+  fi
+
+  if [ $VIEW = "all" -o $VIEW = "ldap" ]; then
+    service_crt=/opt/zimbra/conf/slapd.crt
+    #echo "::service ldap::"
+    if [ -f "${service_crt}" ]; then
+      ${openssl} x509  -in ${service_crt} -noout -checkend ${exp_thres_secs}
+      if [ $? != 0 ]; then
+        status=1
+        echo "${service_crt} is expiring within ${exp_thres_days} days."
+        ${openssl} x509  -in ${service_crt} -enddate -noout 
+      fi
+    else 
+      echo "${ERROR_PREFIX} ${service_crt} does not exist"
+    fi
+  fi
+
+  exit $status
 }
 
 viewdeployedcrt() {
@@ -1328,6 +1452,8 @@ usage () {
   echo "  $0 viewstagedcrt <self|comm> [certfile]"
   echo "  $0 verifycrt <self|comm> [priv_key] [certfile]"
   echo "  $0 verifycrtchain <ca_file> <certfile>"
+  echo "  $0 checkcrtexpiration [-days 30] [service]"
+  echo "  $0 addcacert <certfile>"
   echo "  $0 migrate"
   echo
   echo "Comments:  "
@@ -1345,6 +1471,8 @@ usage () {
   echo "-  deploycrt comm installs the certificates using commercially signed certificate in ${zimbra_comm_cert_directory} "
   echo "-  verifycrt <self|comm> compares openssl md5 [priv_key] and [certfile]."
   echo "-  migrate moves certs/keys from ZCS installs prior to version 5.0.x"
+  echo "-  addcacert appends an otherwise untrusted ssl certificate to the cacerts file."
+  echo "     This is primarily for allowance of untrusted ssl certificates in external data sources."
 
   echo
   
@@ -1386,8 +1514,12 @@ elif [ x"$ACTION" = "xverifycrt" ]; then
   verifycrt $@
 elif [ x"$ACTION" = "xverifycrtkey" ]; then
   verifycrtkey $@
- elif [ x"$ACTION" = "xverifycrtchain" ]; then
+elif [ x"$ACTION" = "xverifycrtchain" ]; then
   verifycrtchain $@
+elif [ x"$ACTION" = "xcheckcrtexpiration" ]; then
+  checkCertExpiration $@
+elif [ x"$ACTION" = "xaddcacert" ]; then
+  addCACERT $@
 elif [ x"$ACTION" = "xmigrate" ]; then
   migrate $@
 elif [ x"$ACTION" = "x-help" -o x"$ACTION" = "xhelp" -o x"$ACTION" = "x-h" -o x"$ACTION" = "x--help" ]; then
