bug: 19791
Integrating from main to FRANK

Change 65274 by jhahm@jhahm-mac on 2007/08/30 14:39:16

	bug: 19791

	Uppercase the METHOD value to work around LiveMeeting bug.


Affected files ...

... //depot/main/ZimbraServer/src/java/com/zimbra/cs/mailbox/Message.java#86 edit
... //depot/main/ZimbraServer/src/java/com/zimbra/cs/mailbox/calendar/Invite.java#89 edit

http://bugzilla.zimbra.com/show_bug.cgi?id=19791

Copied from Perforce
 Change: 65279

diff --git a/src/bin/zmcertinstall b/src/bin/zmcertinstall
--- a/src/bin/zmcertinstall
+++ b/src/bin/zmcertinstall
@@ -16,7 +16,7 @@
 # The Original Code is: Zimbra Collaboration Suite Server.
 # 
 # The Initial Developer of the Original Code is Zimbra, Inc.
-# Portions created by Zimbra are Copyright (C) 2005, 2006, 2007 Zimbra, Inc.
+# Portions created by Zimbra are Copyright (C) 2005, 2006 Zimbra, Inc.
 # All Rights Reserved.
 # 
 # Contributor(s):
@@ -24,44 +24,28 @@
 # ***** END LICENSE BLOCK *****
 # 
 
+BASE=/opt/zimbra/ssl/ssl
 
-if [ x`whoami` != "xzimbra" ]; then
-  echo "$0 must be run as user zimbra"
-  exit 1
-fi
+JAVA_HOME=/opt/zimbra/java
 
-platform=`/opt/zimbra/libexec/get_plat_tag.sh 2> /dev/null` || "unknown"
-source `dirname $0`/zmshutil || exit 1
-zmsetvars \
-  zimbra_home \
-  zimbra_log_directory \
-  zimbra_tmp_directory \
-  zimbra_java_home \
-  mailboxd_directory \
-  mailboxd_keystore \
-  mailboxd_server \
-  postfix_smtpd_tls_cert_file \
-  postfix_smtpd_tls_key_file
+TOMCAT=/opt/zimbra/tomcat/conf
 
-
-
-zimbra_ssl_directory=${zimbra_home}/ssl/ssl
-export JAVA_HOME=$zimbra_java_home
-zimbra_conf_directory=${zimbra_home}/conf
+CONF=/opt/zimbra/conf
+TCONF=/opt/zimbra/tomcat/conf
 
 usage() {
   echo "$0 ldap <certfile> <keyfile>"
   echo "$0 mta <certfile> <keyfile>"
   echo "$0 mailbox [<certfile>]"
-  echo "$0 proxy <certfile> <keyfile>"
-  echo "  Default <certfile> is ${zimbra_ssl_directory}/server/mailboxd.crt"
+  echo "  Default <certfile> is ${BASE}/server/tomcat.crt"
+  exit 1
 }
 
 case "$1" in
-  mta|mailbox|proxy|ldap)
+  mta|mailbox|ldap)
     APP=$1
-    zimbra_tls_certfile=$2
-    zimbra_tls_keysfile=$3
+    CERTFILE=$2
+    KEYFILE=$3
     ;;
   help|-help|--help)
     usage
@@ -74,45 +58,43 @@ case "$1" in
 esac
 
 # ldap requires 2 args
-if [ x"$APP" = "xldap" ] && [ x"${zimbra_tls_certfile}" = "x" -o x"${zimbra_tls_keysfile}" = "x" ]; then
+if [ x"$APP" = "xldap" ] && [ x"${CERTFILE}" = "x" -o x"${KEYFILE}" = "x" ]; then
   usage
   exit 1
 fi
 
 # mta requires 2 args
-if [ x"$APP" = "xmta" ] && [ x"${zimbra_tls_certfile}" = "x" -o x"${zimbra_tls_keysfile}" = "x" ]; then
+if [ x"$APP" = "xmta" ] && [ x"${CERTFILE}" = "x" -o x"${KEYFILE}" = "x" ]; then
   usage
   exit 1
 fi
 
-# proxy requires 2 args
-if [ x"$APP" = "xproxy" ] && [ x"${zimbra_tls_certfile}" = "x" -o x"${zimbra_tls_keysfile}" = "x" ]; then
-  usage
-  exit 1
+if [ "x$CERTFILE" = "x" ]; then
+	CERTFILE=${BASE}/server/tomcat.crt
 fi
 
-if [ "x${zimbra_tls_certfile}" = "x" ]; then
-	zimbra_tls_certfile=${zimbra_ssl_directory}/server/mailboxd.crt
-fi
-
-if [ ! -f "${zimbra_tls_certfile}" ]; then
-	echo "ERROR - ${zimbra_tls_certfile} not found!"
+if [ ! -f $CERTFILE ]; then
+	echo "ERROR - $CERTFILE not found!"
 	exit 1
 fi
 
-mkdir -p ${zimbra_ssl_directory}/server
-mkdir -p ${zimbra_ssl_directory}/cert
-mkdir -p ${zimbra_ssl_directory}/ca
+mkdir -p ${BASE}/server
+mkdir -p ${BASE}/cert
+mkdir -p ${BASE}/ca
 
 
 getHostInfo() {
 
+	platform=`/opt/zimbra/libexec/get_plat_tag.sh`
 	if [ "x$platform" = "xMACOSX" -o "x$platform" = "xMACOSXx86" ]; then
 		HH=`hostname`
 		return
 	else
 		H=`hostname --fqdn`
 	fi
+
+	# $H=$H.zimbrasys.com
+
 	HH=`echo $H | grep '\.'`
 
 	if [ "x$HH" = "x" ]; then
@@ -128,20 +110,14 @@ importCert() {
 	echo
 
 	if [ $APP = "mailbox" ]; then
-		keytool -import -alias ${mailboxd_server} -keystore ${mailboxd_keystore} \
-			-trustcacerts -file ${zimbra_tls_certfile} -storepass zimbra
-	elif [ $APP = "mta" ]; then
-          cp -f ${zimbra_tls_certfile} ${postfix_smtpd_tls_cert_file}
-          cp -f ${zimbra_tls_keysfile} ${postfix_smtpd_tls_key_file}
+		keytool -import -alias tomcat -keystore ${TCONF}/keystore \
+			-trustcacerts -file ${CERTFILE} -storepass zimbra
         elif [ $APP = "ldap" ]; then
-          cp -f ${zimbra_tls_certfile} "/opt/zimbra/conf/slapd.crt"
-          cp -f ${zimbra_tls_keysfile} "/opt/zimbra/conf/slapd.key"
-        elif [ $APP = "proxy" ]; then
-          cp -f ${zimbra_tls_certfile} "/opt/zimbra/conf/nginx.crt"
-          cp -f ${zimbra_tls_keysfile} "/opt/zimbra/conf/nginx.key"
-        else
-          echo "ERROR: Unknown application $APP"
-          exit
+          cp -f $CERTFILE ${CONF}/slapd.crt
+          cp -f $KEYFILE ${CONF}/slapd.key
+	else
+		cp -f $CERTFILE ${CONF}/smtpd.crt
+		cp -f $KEYFILE ${CONF}/smtpd.key
 	fi
 
 }
diff --git a/src/bin/zmtlsctl b/src/bin/zmtlsctl
--- a/src/bin/zmtlsctl
+++ b/src/bin/zmtlsctl
@@ -16,14 +16,13 @@
 # The Original Code is: Zimbra Collaboration Suite Server.
 # 
 # The Initial Developer of the Original Code is Zimbra, Inc.
-# Portions created by Zimbra are Copyright (C) 2005, 2006, 2007 Zimbra, Inc.
+# Portions created by Zimbra are Copyright (C) 2005, 2006 Zimbra, Inc.
 # All Rights Reserved.
 # 
 # Contributor(s):
 # 
 # ***** END LICENSE BLOCK *****
 # 
-
 
 
 if [ x`whoami` != "xzimbra" ]; then
@@ -38,40 +37,18 @@ zmsetvars \
   zimbra_log_directory \
   zimbra_tmp_directory \
   zimbra_java_home \
-  mailboxd_directory 
-platform=`${zimbra_home}/libexec/get_plat_tag.sh 2> /dev/null` || exit 1
-sasl_conf_directory=${zimbra_home}/cyrus-sasl/etc
-if [ x"${mailboxd_directory}" = "${zimbra_home}/tomcat" ]; then
-  mailboxd_server=tomcat
-  mailboxd_conf_directory=${mailboxd_directory}/conf
-else
-  mailboxd_server=jetty
-  mailboxd_conf_directory=${mailboxd_directory}/etc
-fi
-jetty_web_xml=${zimbra_home}/jetty/etc
+  tomcat_directory 
 
-if [ $# -gt 1 ]; then
-    echo "Usage: $0 [mixed|both|http|https|redirect|help]"
-    exit 1
-fi
-  
-case "$1" in
-  mixed|both|http|https|redirect)
-    MODE=$1
-    ;;
-  help|--help|-help)
-    echo "Usage: $0 [mixed|both|http|https|redirect]"
-    exit 0
-    ;;
-  '')
-    ;;
-  *)
-    echo "Usage: $0 [mixed|both|http|https|redirect|help]"
-    exit 1
-    ;;
-esac
-
+MODE=$1
 export JAVA_HOME=${zimbra_java_home}
+
+if [ "x${zimbra_server_hostname}" = "x" ]; then
+  zimbra_server_hostname=`/opt/zimbra/bin/zmhostname`
+  if [ "x${zimbra_server_hostname}" = "x" ]; then
+    echo "ERROR: Unable to determine zmhostname"
+    exit 1;
+  fi
+fi
 
 if [ "x${zimbra_tmp_directory}" = "x" ]; then
   zimbra_tmp_directory=/tmp
@@ -81,10 +58,6 @@ if [ ! -d ${zimbra_tmp_directory} ]; then
   mkdir -p ${zimbra_tmp_directory}
 fi
 
-if [ "x$zimbra_server_hostname" = "x" ]; then
-  echo "ERROR: Unable to determine zmhostname"
-  exit 1;
-fi
 
 ${zimbra_home}/bin/zmprov -l gs ${zimbra_server_hostname} > /dev/null 2>&1
 if [ $? != 0 ]; then
@@ -105,142 +78,55 @@ else
 	shift
 fi
 
-updateTomcatConfig() {
+updateWebConfig() {
 
 	if [ $MODE = "http" ]; then
 		sed -e 's/\(.*HTTPSBEGIN\).*/\1/' -e 's/.*\(HTTPSEND.*\)/\1/' \
 			-e 's/\(.*HTTPBEGIN\).*/\1 -->/' -e 's/.*\(HTTPEND.*\)/<!-- \1/' \
-			${mailboxd_conf_directory}/server.xml > \
+			${zimbra_home}/tomcat/conf/server.xml > \
 			${zimbra_tmp_directory}/server.xml.$$
+		if [ -f ${zimbra_home}/cyrus-sasl/etc/saslauthd.conf.in ]; then
+			sed -e 's/^zimbra_url: https:/zimbra_url: http:/' \
+				${zimbra_home}/cyrus-sasl/etc/saslauthd.conf.in > \
+				${zimbra_tmp_directory}/saslauthd.conf.in.$$
+		fi
 	else
+		if [ -f ${zimbra_home}/cyrus-sasl/etc/saslauthd.conf.in ]; then
+			sed -e 's/^zimbra_url: http:/zimbra_url: https:/' \
+				${zimbra_home}/cyrus-sasl/etc/saslauthd.conf.in > \
+				${zimbra_tmp_directory}/saslauthd.conf.in.$$
+		fi
 		if [ $MODE = "https" ]; then
 			sed -e 's/\(.*HTTPSBEGIN\).*/\1 -->/' -e 's/.*\(HTTPSEND.*\)/<!-- \1/' \
 				-e 's/\(.*HTTPBEGIN\).*/\1/' -e 's/.*\(HTTPEND.*\)/\1/' \
-				${mailboxd_conf_directory}/server.xml > \
+				${zimbra_home}/tomcat/conf/server.xml > \
 				${zimbra_tmp_directory}/server.xml.$$
 		else
 			# MIXED - enable both
 			sed -e 's/\(.*HTTPSBEGIN\).*/\1 -->/' -e 's/.*\(HTTPSEND.*\)/<!-- \1/' \
 				-e 's/\(.*HTTPBEGIN\).*/\1 -->/' -e 's/.*\(HTTPEND.*\)/<!-- \1/' \
-				${mailboxd_conf_directory}/server.xml > \
+				${zimbra_home}/tomcat/conf/server.xml > \
 				${zimbra_tmp_directory}/server.xml.$$
 		fi
 	fi
 	if [ -s ${zimbra_tmp_directory}/server.xml.$$ ]; then
-		mv -f ${zimbra_tmp_directory}/server.xml.$$ \
-      ${mailboxd_conf_directory}/server.xml
-	fi
-	sed -e "s/.*PROTOCOL MODE.*/<env-entry-value>$MODE<\/env-entry-value><!-- PROTOCOL MODE -->/" \
-		${mailboxd_directory}/webapps/zimbra/WEB-INF/web.xml > ${zimbra_tmp_directory}/web.xml.$$
-  if [ -s ${zimbra_tmp_directory}/web.xml.$$ ]; then
-	  mv -f ${zimbra_tmp_directory}/web.xml.$$ ${mailboxd_directory}/webapps/zimbra/WEB-INF/web.xml
-  fi
-	
-}
-
-updateJettyConfig() {
-	if [ $MODE = "http" ]; then
-		sed -e 's/\(.*HTTPSBEGIN\).*/\1/' -e 's/.*\(HTTPSEND.*\)/\1/' \
-			-e 's/\(.*HTTPBEGIN\).*/\1 -->/' -e 's/.*\(HTTPEND.*\)/<!-- \1/' \
-			${mailboxd_conf_directory}/jetty.xml.in > \
-			${zimbra_tmp_directory}/jetty.xml.$$
-		sed -e 's/\(.*REDIRECTBEGIN\).*/\1/' -e 's/.*\(REDIRECTEND.*\)/\1/' \
-			${jetty_web_xml}/zimbra.web.xml.in > \
-			${zimbra_tmp_directory}/zimbra.web.xml.in
-		sed -e 's/\(.*REDIRECTBEGIN\).*/\1/' -e 's/.*\(REDIRECTEND.*\)/\1/' \
-			${jetty_web_xml}/zimbraAdmin.web.xml.in > \
-			${zimbra_tmp_directory}/zimbraAdmin.web.xml.in
-	elif [ $MODE = "https" ]; then
-		sed -e 's/\(.*HTTPSBEGIN\).*/\1 -->/' -e 's/.*\(HTTPSEND.*\)/<!-- \1/' \
-			-e 's/\(.*HTTPBEGIN\).*/\1/' -e 's/.*\(HTTPEND.*\)/\1/' \
-			${mailboxd_conf_directory}/jetty.xml.in > \
-			${zimbra_tmp_directory}/jetty.xml.$$
-		sed -e 's/\(.*REDIRECTBEGIN\).*/\1/' -e 's/.*\(REDIRECTEND.*\)/\1/' \
-			${jetty_web_xml}/zimbra.web.xml.in > \
-			${zimbra_tmp_directory}/zimbra.web.xml.in
-		sed -e 's/\(.*REDIRECTBEGIN\).*/\1/' -e 's/.*\(REDIRECTEND.*\)/\1/' \
-			${jetty_web_xml}/zimbraAdmin.web.xml.in > \
-			${zimbra_tmp_directory}/zimbraAdmin.web.xml.in
-	elif [ $MODE = "redirect" ]; then
-		# redirect - enable both
-		# Then enable the redirect block in web.xml
-		sed -e 's/\(.*HTTPSBEGIN\).*/\1 -->/' -e 's/.*\(HTTPSEND.*\)/<!-- \1/' \
-			-e 's/\(.*HTTPBEGIN\).*/\1 -->/' -e 's/.*\(HTTPEND.*\)/<!-- \1/' \
-			${mailboxd_conf_directory}/jetty.xml.in > \
-			${zimbra_tmp_directory}/jetty.xml.$$
-		sed -e 's/\(.*REDIRECTBEGIN\).*/\1 -->/' -e 's/.*\(REDIRECTEND.*\)/<!-- \1/' \
-			${jetty_web_xml}/zimbra.web.xml.in > \
-			${zimbra_tmp_directory}/zimbra.web.xml.in.$$
-		sed -e 's/\(.*REDIRECTBEGIN\).*/\1 -->/' -e 's/.*\(REDIRECTEND.*\)/<!-- \1/' \
-			${jetty_web_xml}/zimbraAdmin.web.xml.in > \
-			${zimbra_tmp_directory}/zimbraAdmin.web.xml.in.$$
-	else
-		# MIXED - enable both
-		sed -e 's/\(.*HTTPSBEGIN\).*/\1 -->/' -e 's/.*\(HTTPSEND.*\)/<!-- \1/' \
-			-e 's/\(.*HTTPBEGIN\).*/\1 -->/' -e 's/.*\(HTTPEND.*\)/<!-- \1/' \
-			${mailboxd_conf_directory}/jetty.xml.in > \
-			${zimbra_tmp_directory}/jetty.xml.$$
-		sed -e 's/\(.*REDIRECTBEGIN\).*/\1/' -e 's/.*\(REDIRECTEND.*\)/\1/' \
-			${jetty_web_xml}/zimbra.web.xml.in > \
-			${zimbra_tmp_directory}/zimbra.web.xml.in
-		sed -e 's/\(.*REDIRECTBEGIN\).*/\1/' -e 's/.*\(REDIRECTEND.*\)/\1/' \
-			${jetty_web_xml}/zimbraAdmin.web.xml.in > \
-			${zimbra_tmp_directory}/zimbraAdmin.web.xml.in
-	fi
-	if [ -s ${zimbra_tmp_directory}/jetty.xml.$$ ]; then
-		mv -f ${zimbra_tmp_directory}/jetty.xml.$$ \
-      			${mailboxd_conf_directory}/jetty.xml.in
-	fi
-	if [ -s ${zimbra_tmp_directory}/zimbra.web.xml.in.$$ ]; then
-		mv -f ${zimbra_tmp_directory}/zimbra.web.xml.in.$$ \
-			${jetty_web_xml}/zimbra.web.xml.in
-	fi
-	if [ -s ${zimbra_tmp_directory}/zimbraAdmin.web.xml.in.$$ ]; then
-		mv -f ${zimbra_tmp_directory}/zimbraAdmin.web.xml.in.$$ \
-			${jetty_web_xml}/zimbraAdmin.web.xml.in
-	fi
-	if [ $MODE = "redirect" ]; then
-		sed -e "s/.*PROTOCOL MODE.*/<env-entry-value>https<\/env-entry-value><!-- PROTOCOL MODE -->/" \
-			${mailboxd_conf_directory}/zimbra.web.xml.in > ${zimbra_tmp_directory}/web.xml.$$
-        else
-		sed -e "s/.*PROTOCOL MODE.*/<env-entry-value>$MODE<\/env-entry-value><!-- PROTOCOL MODE -->/" \
-			${mailboxd_conf_directory}/zimbra.web.xml.in > ${zimbra_tmp_directory}/web.xml.$$
-	fi
-  if [ -s ${zimbra_tmp_directory}/web.xml.$$ ]; then
-	  mv -f ${zimbra_tmp_directory}/web.xml.$$ ${mailboxd_conf_directory}/zimbra.web.xml.in
-  fi
-  ${zimbra_home}/libexec/zmmtaconfig webxml mailbox
-}
-
-updateSASLConfig() {
-	if [ $MODE = "http" ]; then
-		if [ -f ${sasl_conf_directory}/saslauthd.conf.in ]; then
-			sed -e 's/^zimbra_url: https:/zimbra_url: http:/' \
-				${sasl_conf_directory}/saslauthd.conf.in > \
-				${zimbra_tmp_directory}/saslauthd.conf.in.$$
-		fi
-	else
-		if [ -f ${sasl_conf_directory}/saslauthd.conf.in ]; then
-			sed -e 's/^zimbra_url: http:/zimbra_url: https:/' \
-				${sasl_conf_directory}/saslauthd.conf.in > \
-				${zimbra_tmp_directory}/saslauthd.conf.in.$$
-		fi
+		mv -f ${zimbra_tmp_directory}/server.xml.$$ ${zimbra_home}/tomcat/conf/server.xml
 	fi
 	if [ -s ${zimbra_tmp_directory}/saslauthd.conf.in.$$ ]; then
-		mv -f ${zimbra_tmp_directory}/saslauthd.conf.in.$$ \
-      ${sasl_conf_directory}/saslauthd.conf.in
+		mv -f ${zimbra_tmp_directory}/saslauthd.conf.in.$$ ${zimbra_home}/cyrus-sasl/etc/saslauthd.conf.in
 	fi
 
+	sed -e "s/.*PROTOCOL MODE.*/<env-entry-value>$MODE<\/env-entry-value><!-- PROTOCOL MODE -->/" \
+		${zimbra_home}/tomcat/webapps/zimbra/WEB-INF/web.xml > ${zimbra_tmp_directory}/web.xml.$$
+  if [ -s ${zimbra_tmp_directory}/web.xml.$$ ]; then
+	  mv -f ${zimbra_tmp_directory}/web.xml.$$ ${zimbra_home}/tomcat/webapps/zimbra/WEB-INF/web.xml
+  fi
+	
 }
 
 updateLdap() {
 	${zimbra_home}/bin/zmprov -l ms ${zimbra_server_hostname} zimbraMailMode $MODE
 }
 
-if [ x"${mailboxd_server}" = "xtomcat" ]; then
-  updateTomcatConfig
-else
-  updateJettyConfig
-fi
-updateSASLConfig
+updateWebConfig
 updateLdap
