bug 59988
integrate from main 0.9 to HELIX 0.9

http://bugzilla.zimbra.com/show_bug.cgi?id=59988

Copied from Perforce
 Change: 325994

diff --git a/src/bin/zmclamdctl b/src/bin/zmclamdctl
--- a/src/bin/zmclamdctl
+++ b/src/bin/zmclamdctl
@@ -28,6 +28,7 @@ zmsetvars \
 
 
 pidfile=${zimbra_log_directory}/clamd.pid
+fpidfile=${zimbra_log_directory}/freshclam.pid
 
 if [ ! -d "/opt/zimbra/data/clamav/db" ]; then
     mkdir -p /opt/zimbra/data/clamav/db
@@ -40,6 +41,9 @@ rewriteconfig() {
 getpid() {
   if [ -f $pidfile ]; then
     cpid=`cat $pidfile`
+  fi
+  if [ -f $fpidfile ]; then
+    fpid=`cat $fpidfile`
   fi
 }
 
@@ -56,6 +60,19 @@ checkrunning() {
       running=0
     else
       running=1
+    fi
+  fi
+  # freshclam
+  if [ "x$fpid" = "x" ]; then
+    frunning=0
+  else
+    kill -0 $fpid 2> /dev/null
+    if [ $? != 0 ]; then
+      rm $fpidfile
+      fpid=""
+      frunning=0
+    else
+      frunning=1
     fi
   fi
 }
@@ -84,12 +101,25 @@ case "$1" in
         ${zimbra_home}/data/clamav/db/daily.cvd
       cp -f ${zimbra_home}/clamav/db/main.cvd.init \
         ${zimbra_home}/data/clamav/db/main.cvd
+      # Init the db
+      ${zimbra_home}/clamav/bin/freshclam --quiet \
+        --config-file=${zimbra_home}/conf/freshclam.conf &
     fi
     if [ x$2 = "x" ]; then
       rewriteconfig
     fi
 
     checkrunning
+    echo -n "Starting freshclam..."
+    if [ $frunning = 1 ]; then
+      echo "freshclam is already running.";
+    else
+      ${zimbra_home}/clamav/bin/freshclam \
+        --config-file=${zimbra_home}/conf/freshclam.conf --quiet --daemon --checks=12 \
+          >> ${zimbra_log_directory}/freshclam.log 2>&1 &
+      echo "done."
+    fi
+
     echo -n "Starting clamd..."
     if [ $running = 1 ]; then
       echo "clamd is already running.";
@@ -113,16 +143,35 @@ case "$1" in
    ;;
   
   'kill')
+    if [ -f /opt/zimbra/log/freshclam.pid ]; then
+      cpid=`cat /opt/zimbra/log/freshclam.pid`
+      kill -9 "$cpid" 2> /dev/null
+    fi
     if [ -f /opt/zimbra/log/clamd.pid ]; then
       cpid=`cat /opt/zimbra/log/clamd.pid`
       kill -9 "$cpid" 2> /dev/null
     fi
+    pskillall -9 ${zimbra_home}/clamav/bin/freshclam
     pskillall -9 ${zimbra_home}/clamav/sbin/clamd
     exit 0
    ;;
 
   'stop')
     checkrunning
+    echo -n "Stopping freshclam..."
+    if [ $frunning = 0 ]; then
+      echo "freshclam is not running.";
+    else 
+      if [ x"$fpid" != "x" ]; then  
+        kill -9 "$fpid" 2> /dev/null
+        if [ $? = 0 ]; then
+          echo "done."
+        else 
+          echo "failed."
+        fi
+      fi
+    fi
+
     echo -n "Stopping clamd..."
     if [ $running = 0 ]; then
       echo "clamd is not running.";
