Integrating from HELIX..
Change 325250 by vmahajan@vmahajan_macbook on 2011/08/10 21:24:36

        bug: 63183 - remove zimbraPrefCalendarReminderSendEmail upgrade step

http://bugzilla.zimbra.com/show_bug.cgi?id=63183

Copied from Perforce
 Change: 325253

diff --git a/src/bin/zmfreshclamctl b/src/bin/zmfreshclamctl
--- a/src/bin/zmfreshclamctl
+++ b/src/bin/zmfreshclamctl
@@ -27,35 +27,31 @@ zmsetvars \
   zimbra_log_directory
 
 
-pidfile=${zimbra_log_directory}/clamd.pid
-
-if [ ! -d "/opt/zimbra/data/clamav/db" ]; then
-    mkdir -p /opt/zimbra/data/clamav/db
-fi
+fpidfile=${zimbra_log_directory}/freshclam.pid
 
 rewriteconfig() {
   /opt/zimbra/libexec/configrewrite antivirus > /dev/null 2>&1
 }
 
 getpid() {
-  if [ -f $pidfile ]; then
-    cpid=`cat $pidfile`
+  if [ -f $fpidfile ]; then
+    fpid=`cat $fpidfile`
   fi
 }
 
 checkrunning() {
   getpid
-  # clamd
-  if [ "x$cpid" = "x" ]; then
-    running=0
+  # freshclam
+  if [ "x$fpid" = "x" ]; then
+    frunning=0
   else
-    kill -0 $cpid 2> /dev/null
+    kill -0 $fpid 2> /dev/null
     if [ $? != 0 ]; then
-      rm $pidfile
-      cpid=""
-      running=0
+      rm $fpidfile
+      fpid=""
+      frunning=0
     else
-      running=1
+      frunning=1
     fi
   fi
 }
@@ -78,74 +74,48 @@ pskillall() {
 case "$1" in
   'start')
 
-    if [ ! -f ${zimbra_home}/data/clamav/db/daily.cvd ]; then
-      # Start with the files we ship.
-      cp -f ${zimbra_home}/clamav/db/daily.cvd.init \
-        ${zimbra_home}/data/clamav/db/daily.cvd
-      cp -f ${zimbra_home}/clamav/db/main.cvd.init \
-        ${zimbra_home}/data/clamav/db/main.cvd
-    fi
     if [ x$2 = "x" ]; then
       rewriteconfig
     fi
 
     checkrunning
-    echo -n "Starting clamd..."
-    if [ $running = 1 ]; then
-      echo "clamd is already running.";
+    echo -n "Starting freshclam..."
+    if [ $frunning = 1 ]; then
+      echo "freshclam is already running.";
     else
-      ${zimbra_home}/clamav/sbin/clamd \
-        --config-file=${zimbra_home}/conf/clamd.conf \
-          >> ${zimbra_log_directory}/clamd.log 2>&1 &
-  
-      for ((i = 0; i < 12; i++)); do
-        checkrunning
-        if [ $running = 1 ]; then
-          echo "done."
-        exit 0
-        fi
-        sleep 5
-      done
-      echo "failed."
-      exit 1
+      ${zimbra_home}/clamav/bin/freshclam \
+        --config-file=${zimbra_home}/conf/freshclam.conf --quiet --daemon --checks=12 \
+          >> ${zimbra_log_directory}/freshclam.log 2>&1 &
+      echo "done."
     fi
     exit 0
    ;;
   
   'kill')
-    if [ -f /opt/zimbra/log/clamd.pid ]; then
-      cpid=`cat /opt/zimbra/log/clamd.pid`
+    if [ -f /opt/zimbra/log/freshclam.pid ]; then
+      cpid=`cat /opt/zimbra/log/freshclam.pid`
       kill -9 "$cpid" 2> /dev/null
     fi
-    pskillall -9 ${zimbra_home}/clamav/sbin/clamd
+    pskillall -9 ${zimbra_home}/clamav/bin/freshclam
     exit 0
    ;;
 
   'stop')
     checkrunning
-    echo -n "Stopping clamd..."
-    if [ $running = 0 ]; then
-      echo "clamd is not running.";
-    else
-      if [ x"$cpid" != "x" ]; then
-        kill -TERM "$cpid" 2> /dev/null
-      fi
-      for ((i = 0; i < 30; i++)); do
-        sleep 2
-        kill -0 $cpid 2> /dev/null
-        if [ $? != 0 ]; then
-          rm -f ${pidfile}
-          break
+    echo -n "Stopping freshclam..."
+    if [ $frunning = 0 ]; then
+      echo "freshclam is not running.";
+    else 
+      if [ x"$fpid" != "x" ]; then  
+        kill -9 "$fpid" 2> /dev/null
+        if [ $? = 0 ]; then
+          echo "done."
+        else 
+          echo "failed."
         fi
-        kill $cpid
-      done
-      if [ -s ${pidfile} ]; then
-        echo "failed."
-        exit 1
-      else
-        echo "done."
       fi
     fi
+
     exit 0
   ;;
   
@@ -156,8 +126,8 @@ case "$1" in
   
   'status')
     checkrunning
-    echo -n "clamd is "
-    if [ $running = 1 ]; then
+    echo -n "freshclam is "
+    if [ $frunning = 1 ]; then
       echo "running."
       exit 0
     else
