ZCS-13390:zmlicenseservice utility for license daemon service

diff --git a/src/bin/zmlicenseservice b/src/bin/zmlicenseservice
--- a/src/bin/zmlicenseservice
+++ b/src/bin/zmlicenseservice
@@ -25,6 +25,7 @@ ZMJAVA="/opt/zimbra/common/lib/jvm/java/bin/java"
 LD_LIBRARY_PATH="/opt/zimbra/license/lib"
 LICENSE_DAEMON_SERVICE_OUTPUT="/opt/zimbra/log/license-daemon-service.log"
 LICENSE_DAEMON_SERVICE="/opt/zimbra/license/lib/app.jar"
+LICENSE_DAEMON_SERVICE_PORT="8081"
 pid=""
 
 checkrunning()
@@ -50,9 +51,9 @@ startLicenseDaemonService()
 		kill -9 ${pid}
 	fi
 	if [ -f ${LD_LIBRARY_PATH}/libShafer-dev-linux64.so ]; then
-		export LD_LIBRARY_PATH; nohup ${ZMJAVA} -jar $LICENSE_DAEMON_SERVICE --spring.profiles.active=dev --server.port=8081 > $LICENSE_DAEMON_SERVICE_OUTPUT 2>&1 &
+		export LD_LIBRARY_PATH; nohup ${ZMJAVA} -jar $LICENSE_DAEMON_SERVICE --spring.profiles.active=dev --server.port=$LICENSE_DAEMON_SERVICE_PORT > $LICENSE_DAEMON_SERVICE_OUTPUT 2>&1 &
 	else
-		export LD_LIBRARY_PATH; nohup ${ZMJAVA} -jar $LICENSE_DAEMON_SERVICE --server.port=8081 > $LICENSE_DAEMON_SERVICE_OUTPUT 2>&1 &
+		export LD_LIBRARY_PATH; nohup ${ZMJAVA} -jar $LICENSE_DAEMON_SERVICE --server.port=$LICENSE_DAEMON_SERVICE_PORT > $LICENSE_DAEMON_SERVICE_OUTPUT 2>&1 &
 	fi
 	sleep 5
 	checkrunning
@@ -76,17 +77,17 @@ case "$1" in
 	checkrunning
 	echo -n "Stopping license daemon service..."
 	if [ $running -lt 1 ]; then
-	  echo "license daemon service is not running."
-	  exit 0
+		echo "license daemon service is not running."
+		exit 0
 	else 
 		kill -9 $pid 2> /dev/null
 		if [ $? != 0 ]; then
-		  echo "failed."
-		  exit 1
-	   else
-		  echo "done."
-		  exit 0
-	   fi
+			echo "failed."
+			exit 1
+		else
+			echo "done."
+			exit 0
+		fi
 	fi
   ;;
 
@@ -99,11 +100,11 @@ case "$1" in
 	echo -n "license daemon service is "
 	checkrunning
 	if [ $running -lt 1 ]; then
-	  echo "not running." 
-	  exit 1
+		echo "not running."
+		exit 1
 	else
-	  echo "running."
-	  exit 0
+		echo "running."
+		exit 0
 	fi
    ;;
 	
