ZCS-15348:nalpeiron-daemon service should not get stopped with zmcontrol stop

diff --git a/src/bin/zmlicensectl b/src/bin/zmlicensectl
--- a/src/bin/zmlicensectl
+++ b/src/bin/zmlicensectl
@@ -47,7 +47,7 @@ startLicenseDaemonService()
 		echo "license daemon service is already running."
 		return
 	fi
-	/opt/zimbra/bin/zmprov -l gs `/opt/zimbra/bin/zmhostname` zimbraServiceEnabled | grep -qw license-daemon
+	/opt/zimbra/bin/zmprov -l gs `/opt/zimbra/bin/zmhostname` zimbraServiceEnabled 2>/dev/null | grep -qw license-daemon
 	if [ $? = 1 ]; then
 		echo "license daemon service is not enabled!  failed."
 		err=1
@@ -237,6 +237,12 @@ startNalpeironDaemonService() {
 	echo -n "Starting nalpeiron daemon service..."
 	if [ $nalpeironDaemonServiceRunning = 1 ]; then
 		echo "nalpeiron daemon service is already running."
+		return
+	fi
+	/opt/zimbra/bin/zmprov -l gs `/opt/zimbra/bin/zmhostname` zimbraServiceEnabled 2>/dev/null | grep -qw nalpeiron-daemon
+	if [ $? = 1 ]; then
+		echo "nalpeiron daemon service is not enabled!  failed."
+		err=1
 		return
 	fi
 	if ! sudo systemctl start nalpdaemon &>/dev/null;  then
