Integrated the following from //depot/zimbra/JUDASPRIEST/...: Change 546954 by psurana@psurana-mac on 2015/06/09 09:43:41
bug: 84629
Added logger statement. 
Coverted LC value in millis. 
log4.properties set log4j.logger.zimbra.session=DEBUG

tweak 
zmlocalconfig -e zimbra_active_waitset_timeout_minutes=2

restart mailboxd 

see 
2015-06-09 20:09:17,480 DEBUG [Timer-Zimbra] [] session - active waitset timeout = 120000 ms


tweak 
zmlocalconfig -e zimbra_active_waitset_timeout_minutes=1

restart mailboxd 


psurana:ZimbraServer psurana$ grep "active waitset timeout" /opt/zimbra/log/mailbox.log
2015-06-09 20:01:23,780 DEBUG [Timer-Zimbra] [] session - active waitset timeout = 60000 ms
2015-06-09 20:02:23,781 DEBUG [Timer-Zimbra] [] session - active waitset timeout = 60000 ms
2015-06-09 20:03:23,782 DEBUG [Timer-Zimbra] [] session - active waitset timeout = 60000 ms

https://bugzilla.zimbra.com/show_bug.cgi?id=84629

Copied from Perforce
 Change: 546985

diff --git a/src/bin/zmnginxctl b/src/bin/zmnginxctl
--- a/src/bin/zmnginxctl
+++ b/src/bin/zmnginxctl
@@ -2,7 +2,7 @@
 # 
 # ***** BEGIN LICENSE BLOCK *****
 # Zimbra Collaboration Suite Server
-# Copyright (C) 2008, 2009, 2010, 2013, 2014 Zimbra, Inc.
+# Copyright (C) 2008, 2009, 2010, 2011, 2012, 2013, 2014 Zimbra, Inc.
 # 
 # This program is free software: you can redistribute it and/or modify it under
 # the terms of the GNU General Public License as published by the Free Software Foundation,
@@ -17,14 +17,14 @@
 # 
 
 if [ x`whoami` != xzimbra ]; then
-    echo Error: must be run as zimbra user
+    echo "Error: must be run as zimbra user"
   exit 1
 fi
 
 source `dirname $0`/zmshutil || exit 1
 zmsetvars
 
-servicename=memcached
+servicename=nginx
 configfile=/opt/zimbra/conf/${servicename}.conf
 pidfile=${zimbra_log_directory}/${servicename}.pid
 pid=""
@@ -54,10 +54,13 @@ checkrunning()
 
 case "$1" in 
   start)
-
-    if [ ! -L /opt/zimbra/memcached ]; then
-      echo "Error: memcached not installed"
+    if [ ! -L /opt/zimbra/nginx ]; then
+      echo "Error: nginx not installed"
       exit 1
+    fi
+
+    if [ ! -f ${configfile} ]; then
+      echo "${configfile} is missing."
     fi
 
     checkrunning
@@ -66,8 +69,26 @@ case "$1" in
       echo "${servicename} is already running."
       exit 0
     fi
+    if [ "x$2" = "x" ]; then
+      /opt/zimbra/libexec/configrewrite proxy > /dev/null 2>&1
+    fi
 
-    /opt/zimbra/${servicename}/bin/${servicename} -d -P ${pidfile}
+    if [ ! -f ${configfile} ]; then
+      echo "failed.  ${configfile} is missing."
+      exit 1
+    fi
+
+    # read the last line of nginx.conf which indicates the conf gen result
+    res=`tail -n 1 ${configfile}`
+    if ! [[ $res =~ __SUCCESS__ ]]; then
+        echo "failed."
+        msg=`echo $res | awk -F ':' '{print $2}'`
+        if [ x"$msg" = "x" ]; then msg="unknown"; fi
+        echo "nginx start failed. reason: $msg"
+        exit 1
+    fi
+
+    sudo /opt/zimbra/${servicename}/sbin/${servicename} -c ${configfile}
     for ((i=0; i < 30; i++)); do
       checkrunning
       if [ $running = 1 ]; then
@@ -93,10 +114,9 @@ case "$1" in
       for ((i = 0; i < 30; i++)); do
         kill -0 $pid 2> /dev/null
         if [ $? != 0 ]; then
-          rm -rf ${pidfile}
           break
         fi
-        kill -9 $pid
+        kill -TERM $pid
         sleep 1
       done
     fi
@@ -110,7 +130,7 @@ case "$1" in
   ;;
   restart)
     $0 stop
-    $0 start
+    $0 start $2
   ;;
   reload)
     checkrunning
