Integrate change 531664 from JUDASPRIEST
  	bug: 95933

Reinstate old checkpoint increments; except when always on 'mode' is enabled. This enables the system to keep operating with data which was created in 8.0.x and which is therefore expected to have gaps between mail_item_checkpoint and max(mail_item.id); as well as reducing the number of DB writes for normal (non 'alwayson') operation.

https://bugzilla.zimbra.com/show_bug.cgi?id=95933

Copied from Perforce
 Change: 531668

diff --git a/src/bin/zmproxyctl b/src/bin/zmproxyctl
--- a/src/bin/zmproxyctl
+++ b/src/bin/zmproxyctl
@@ -2,7 +2,7 @@
 # 
 # ***** BEGIN LICENSE BLOCK *****
 # Zimbra Collaboration Suite Server
-# Copyright (C) 2007, 2008, 2009, 2010, 2013, 2014 Zimbra, Inc.
+# Copyright (C) 2008, 2009, 2010, 2011, 2012, 2013, 2014 Zimbra, Inc.
 # 
 # This program is free software: you can redistribute it and/or modify it under
 # the terms of the GNU General Public License as published by the Free Software Foundation,
@@ -16,39 +16,144 @@
 # ***** END LICENSE BLOCK *****
 # 
 
-BASE=/opt/zimbra
-SCRIPTS="zmnginxctl"
+if [ x`whoami` != xzimbra ]; then
+    echo "Error: must be run as zimbra user"
+  exit 1
+fi
+
+source `dirname $0`/zmshutil || exit 1
+zmsetvars
+
+servicename=proxy
+configfile=/opt/zimbra/conf/nginx.conf
+pidfile=${zimbra_log_directory}/nginx.pid
+pid=""
+
+getpid()
+{
+  if [ -f ${pidfile} ]; then
+    pid=$(cat ${pidfile})
+  fi
+}
+
+checkrunning()
+{
+  getpid
+  if [ "x$pid" = "x" ]; then
+    running=0
+  else
+    kill -0 $pid 2> /dev/null
+    if [ $? != 0 ]; then
+      pid=""
+      running=0
+    else
+      running=1
+    fi
+  fi
+}
 
 case "$1" in 
-	start)
-		for i in $SCRIPTS; do
-			/opt/zimbra/bin/$i start $2
-		done
-	;;
-	stop)
-		for i in $SCRIPTS; do
-			/opt/zimbra/bin/$i stop $2
-		done
-	;;
-	restart|reload)
-		for i in $SCRIPTS; do
-			/opt/zimbra/bin/$i $1 $2
-		done
-	;;
-	status)
-		STATUS=0
-		for i in $SCRIPTS; do
-		  /opt/zimbra/bin/$i status > /dev/null 2>&1
-		  R=$?
-			if [ $R -ne "0" ]; then
-				echo "$i is not running"
-				STATUS=$R
-			fi
-		done
-		exit $STATUS
-	;;
-	*)
-		echo "$0 start|stop|restart|reload|status"
-		exit 1
-	;;
+  start)
+    if [ ! -L /opt/zimbra/nginx ]; then
+      echo "Error: nginx not installed"
+      exit 1
+    fi
+
+    if [ ! -f ${configfile} ]; then
+      echo "${configfile} is missing."
+    fi
+
+    checkrunning
+    echo -n "Starting ${servicename}..."
+    if [ $running = 1 ]; then
+      echo "${servicename} is already running."
+      exit 0
+    fi
+    if [ "x$2" = "x" ]; then
+      /opt/zimbra/libexec/configrewrite proxy > /dev/null 2>&1
+    fi
+
+    if [ ! -f ${configfile} ]; then
+      echo "failed.  ${configfile} is missing."
+      exit 1
+    fi
+
+    # read the last line of nginx.conf which indicates the conf gen result
+    res=`tail -n 1 ${configfile}`
+    if ! [[ $res =~ __SUCCESS__ ]]; then
+        echo "failed."
+        msg=`echo $res | awk -F ':' '{print $2}'`
+        if [ x"$msg" = "x" ]; then msg="unknown"; fi
+        echo "nginx start failed. reason: $msg"
+        exit 1
+    fi
+
+    sudo /opt/zimbra/nginx/sbin/nginx -c ${configfile}
+    for ((i=0; i < 30; i++)); do
+      checkrunning
+      if [ $running = 1 ]; then
+        break
+      fi
+      sleep 1
+    done
+    if [ "x$pid" != "x" ]; then
+      echo "done."
+      exit 0
+    else
+      echo "failed."
+      exit 1
+    fi
+  ;;
+  stop)
+    checkrunning
+    echo -n "Stopping ${servicename}..."
+    if [ $running = 0 ]; then
+      echo "${servicename} is not running."
+      exit 0
+    else
+      for ((i = 0; i < 30; i++)); do
+        kill -0 $pid 2> /dev/null
+        if [ $? != 0 ]; then
+          break
+        fi
+        kill -TERM $pid
+        sleep 1
+      done
+    fi
+    if [ -s ${pidfile} ]; then
+      echo "failed."
+      exit 1
+    else
+      echo "done."
+    fi
+    exit 0
+  ;;
+  restart)
+    $0 stop
+    $0 start $2
+  ;;
+  reload)
+    checkrunning
+    if [ $running = 1 -a "x$pid" != "x" ]; then
+      echo -n "Reloading ${servicename}..."
+      kill -HUP $pid
+      echo "done."
+    fi
+    
+  ;;
+  status)
+    echo -n "${servicename} is "
+    checkrunning
+    if [ $running = 0 ]; then
+      echo "not running."
+      exit 1
+    else
+      echo "running."
+      exit 0
+    fi
+  ;;
+  *)
+    echo "$0 start|stop|restart|reload|status"
+    exit 1
+  ;;
 esac
