bug: none If ldap server was converted to using mdb, detect and exit
Copied from Perforce
 Change: 490735

diff --git a/src/libexec/zmldapenablereplica b/src/libexec/zmldapenablereplica
--- a/src/libexec/zmldapenablereplica
+++ b/src/libexec/zmldapenablereplica
@@ -137,6 +137,11 @@ verifySyncProv() {
 		echo 'Error: Syncprov already enabled. Exiting...'
 		exit 1
 	fi
+	ARGS="-x -H ldapi:/// -D cn=config -w ${ldap_root_password} -b olcOverlay={0}syncprov,olcDatabase={2}mdb,cn=config -s base"
+	if [ $? -eq 0 ]; then
+		echo 'Error: Syncprov already enabled. Exiting...'
+		exit 1
+	fi
 }
 
 enableSyncProv() {
