bug: 38266
integrate change 159503 from FRANKLIN to main
----------------------------------------------
Change 159503 by pshao@pshao-mac on 2009/05/27 15:16:34

        bug: 38266

        added LC key ldap_cache_external_domain_maxsize(default 2000 entries) and ldap_cache_external_domain_maxage(default 15 minutes) for controlling the non-existing(external) domain cache size/TTL.


Affected files ...

... //depot/FRANKLIN/ZimbraCommon/src/java/com/zimbra/common/localconfig/LC.java#97 edit
... //depot/FRANKLIN/ZimbraServer/src/java/com/zimbra/cs/account/DomainCache.java#3 edit
... //depot/FRANKLIN/ZimbraServer/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java#81 edit

http://bugzilla.zimbra.com/show_bug.cgi?id=38266

Copied from Perforce
 Change: 159504

diff --git a/src/libexec/zmmyinit b/src/libexec/zmmyinit
--- a/src/libexec/zmmyinit
+++ b/src/libexec/zmmyinit
@@ -1,9 +1,8 @@
 #!/bin/bash
 # 
 # ***** BEGIN LICENSE BLOCK *****
-# 
 # Zimbra Collaboration Suite Server
-# Copyright (C) 2004, 2005, 2006 Zimbra, Inc.
+# Copyright (C) 2004, 2005, 2006, 2007, 2008 Zimbra, Inc.
 # 
 # The contents of this file are subject to the Yahoo! Public License
 # Version 1.0 ("License"); you may not use this file except in
@@ -12,13 +11,22 @@
 # 
 # Software distributed under the License is distributed on an "AS IS"
 # basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
-# 
 # ***** END LICENSE BLOCK *****
 # 
 
+if [ x`whoami` != "xzimbra" ]; then
+  echo "Error: must be run as user zimbra"
+  exit 1
+fi
+
+usage() {
+  echo "$0 [--help] [--sql_root_pw <password>] [--mysql_memory_percent 30]"
+  echo "  --sql_root_pw defaults to random password if not specified."
+  echo "  --mysql_memory_percent defaults to 30 percent if not specified."
+}
+
 source `dirname $0`/../bin/zmshutil || exit 1
 zmsetvars -f
-sql_root_pw=$1
 
 #
 # Sanity checks
@@ -31,6 +39,41 @@ zmassert -x ${zimbra_home}/bin/zmmypasswd
 zmassert -x ${mysql_directory}/bin/mysql_install_db
 zmassert -r ${zimbra_db_directory}/db.sql
 zmassert -r ${zimbra_db_directory}/versions-init.sql
+
+for opt in "$@"; do
+  case "$opt" in
+    -help|--help|-h|--help)
+      usage
+      exit 0
+      shift
+      ;;
+    -verbose|--verbose|-v|--v)
+      verbose=yes
+      shift
+      ;;
+    --sql_root_pw)
+      shift
+      sql_root_pw=$1
+      shift
+      ;;
+    --mysql_memory_percent)
+      shift
+      mysql_memory_percent=$1
+      shift
+      ;;
+    --*|-*)
+      echo "Unknown option $opt"
+      usage
+      exit 1
+      shift
+      ;;
+  esac
+done
+
+mysql_memory_percent=${mysql_memory_percent:=30}
+if [ x"$verbose" = "xyes" ]; then
+  echo "mysql_memory_percent=$mysql_memory_percent"
+fi
 
 #
 # Create necessary directories
@@ -46,7 +89,8 @@ mkdir -p ${zimbra_log_directory}
 #
 echo '*' Generating mysql config ${mysql_mycnf}
 rm -f ${mysql_mycnf}
-${zimbra_home}/libexec/zmmycnf > ${mysql_mycnf}
+${zimbra_home}/libexec/zmmycnf --innodb-buffer-pool-memory-percent \
+  $mysql_memory_percent > ${mysql_mycnf}
 
 #
 # Create database
@@ -121,3 +165,4 @@ ${zimbra_home}/bin/mysqladmin -u root --password= password ${mysql_root_password
 
 echo '*' Changing mysql zimbra user password
 ${zimbra_home}/bin/zmmypasswd ${zimbra_mysql_password}
+
