http://bugzilla.zimbra.com/show_bug.cgi?id=7223 bug: 7223
Copied from Perforce
 Change: 24833

diff --git a/src/libexec/zmsetservername b/src/libexec/zmsetservername
--- a/src/libexec/zmsetservername
+++ b/src/libexec/zmsetservername
@@ -26,14 +26,16 @@
 
 NAME=$1
 
-if [ "x$NAME" = "x--help" -o "x$NAME" = "x-h" ]; then
-	echo "Usage: $0 <servername>"
-	echo "Change the name of the Zimbra server"
+if [ "x$NAME" = "x" ]; then
+	echo "New server name required!"
 	exit 1
 fi
 
-if [ "x$NAME" = "x" ]; then
-	echo "New server name required!"
+echo $NAME | egrep '^-' > /dev/null 2>&1
+
+if [ $? -eq 0 ]; then
+	echo "Usage: $0 <servername>"
+	echo "Change the name of the Zimbra server"
 	exit 1
 fi
 
