bug: 19562 integrate change 66766 from main -> FRANK
http://bugzilla.zimbra.com/show_bug.cgi?id=19562

Copied from Perforce
 Change: 66767

diff --git a/src/libexec/zmsetservername b/src/libexec/zmsetservername
--- a/src/libexec/zmsetservername
+++ b/src/libexec/zmsetservername
@@ -16,7 +16,7 @@
 # The Original Code is: Zimbra Collaboration Suite Server.
 # 
 # The Initial Developer of the Original Code is Zimbra, Inc.
-# Portions created by Zimbra are Copyright (C) 2005, 2006, 2007 Zimbra, Inc.
+# Portions created by Zimbra are Copyright (C) 2005, 2006 Zimbra, Inc.
 # All Rights Reserved.
 # 
 # Contributor(s):
@@ -24,46 +24,36 @@
 # ***** END LICENSE BLOCK *****
 # 
 
-source /opt/zimbra/bin/zmshutil || exit 1
-zmsetvars -f zimbra_home
-
-usage() {
-	echo "Usage: $0 <servername>"
-	echo "Change the name of the Zimbra server"
-	exit 1
-}
-
-case "$1" in
-  help|-help|--help)
-    usage
-    ;;
-  *)
-    NAME=$1
-    ;;
-esac
+NAME=$1
 
 if [ "x$NAME" = "x" ]; then
-  usage
+	echo "New server name required!"
+	exit 1
 fi
 
 echo $NAME | egrep '^-' > /dev/null 2>&1
+
 if [ $? -eq 0 ]; then
-  usage
+	echo "Usage: $0 <servername>"
+	echo "Change the name of the Zimbra server"
+	exit 1
 fi
 
+source /opt/zimbra/bin/zmshutil || exit 1
+zmsetvars -f zimbra_home
 
-SERVICES=`${zimbra_home}/bin/zmprov -l gs ${zimbra_server_hostname} | sed -ne '/^zimbraServiceEnabled/ s/zimbraServiceEnabled: //p'`
+SERVICES=`/opt/zimbra/bin/zmprov -l gs ${zimbra_server_hostname} | sed -ne '/^zimbraServiceEnabled/ s/zimbraServiceEnabled: //p'`
 
-${zimbra_home}/bin/zmcontrol stop
+/opt/zimbra/bin/zmcontrol stop
 sleep 10
 
 if [ "x${ldap_is_master}" = "xtrue" ]; then
 	ldap start
 fi
 
-${zimbra_home}/openldap/bin/ldapsearch -H ${ldap_master_url} -w ${ldap_root_password} -D "${zimbra_ldap_userdn}" -b '' -x -LLL "(cn=${zimbra_server_hostname})" | sed -e "s/${zimbra_server_hostname}/${NAME}/g" > /tmp/server.ldif
+/opt/zimbra/openldap/bin/ldapsearch -H ${ldap_master_url} -w ${ldap_root_password} -D "${zimbra_ldap_userdn}" -x -b '' -LLL "(cn=${zimbra_server_hostname})" | sed -e "s/${zimbra_server_hostname}/${NAME}/g" > /tmp/server.ldif
 
-${zimbra_home}/openldap/bin/ldapsearch -H ${ldap_master_url} -w ${ldap_root_password} -D "${zimbra_ldap_userdn}" -b '' -x -LLL "(zimbraMailHost=${zimbra_server_hostname})" dn > /tmp/users.ldif
+/opt/zimbra/openldap/bin/ldapsearch -H ${ldap_master_url} -w ${ldap_root_password} -D "${zimbra_ldap_userdn}" -x -b '' -LLL "(zimbraMailHost=${zimbra_server_hostname})" dn > /tmp/users.ldif
 
 cat /dev/null > /tmp/newusers.ldif
 while read i; do
@@ -82,15 +72,15 @@ EOF
 fi
 done < /tmp/users.ldif
 
-${zimbra_home}/openldap/bin/ldapmodify -c -H ${ldap_master_url} -w ${ldap_root_password} -D "${zimbra_ldap_userdn}" -x -f /tmp/newusers.ldif -v
+/opt/zimbra/openldap/bin/ldapmodify -c -H ${ldap_master_url} -w ${ldap_root_password} -D "${zimbra_ldap_userdn}" -x -f /tmp/newusers.ldif -v
 
-${zimbra_home}/openldap/bin/ldapdelete -H ${ldap_master_url} -w ${ldap_root_password} -D "${zimbra_ldap_userdn}" -x "cn=${zimbra_server_hostname},cn=servers,cn=zimbra"
+/opt/zimbra/openldap/bin/ldapdelete -H ${ldap_master_url} -w ${ldap_root_password} -D "${zimbra_ldap_userdn}" -x "cn=${zimbra_server_hostname},cn=servers,cn=zimbra"
 
-${zimbra_home}/openldap/bin/ldapadd -a -H ${ldap_master_url} -w ${ldap_root_password} -D "${zimbra_ldap_userdn}" -x -f /tmp/server.ldif
+/opt/zimbra/openldap/bin/ldapadd -a -H ${ldap_master_url} -w ${ldap_root_password} -D "${zimbra_ldap_userdn}" -x -f /tmp/server.ldif
 
-LHN=`${zimbra_home}/bin/zmprov -l gcf zimbraLogHostName | sed -e 's/zimbraLogHostName: //'`
+LHN=`/opt/zimbra/bin/zmprov -l gcf zimbraLogHostName | sed -e 's/zimbraLogHostName: //'`
 if [ x$LHN = x${zimbra_server_hostname} ]; then
-	${zimbra_home}/bin/zmprov -l mcf zimbraLogHostName ${NAME}
+	/opt/zimbra/bin/zmprov -l mcf zimbraLogHostName ${NAME}
 fi
 
 zmlocalconfig -e zimbra_server_hostname=${NAME}
@@ -140,7 +130,7 @@ zmsetvars -f
 echo $SERVICES | grep -q mta
 if [ $? == 0 ]; then
   echo -n "Reinitializing the mta config..."
-  ${zimbra_home}/libexec/zmmtainit ${ldap_host} ${ldap_port}
+  /opt/zimbra/libexec/zmmtainit ${ldap_host} ${ldap_port}
   echo "done."
 fi
 
@@ -148,5 +138,5 @@ fi
 echo $SERVICES | grep -q snmp
 if [ $? == 0 ]; then
   echo -n "Reinitializing snmp config..."
-  ${zimbra_home}/libexec/zmsnmpinit
+  /opt/zimbra/libexec/zmsnmpinit
 fi
